### ISSUE TITLE
Can not get syntax highlights for style tag with double-quoted value in its `type`

### ISSUE THREAD

**Issue by aMarCruz** [dekimasoon/language-riot-tag#1]
@dekimasoon , thanks for your work.
In the following tag the styles are not highlighted:

``` html
<less-import>
  <button/>
  <style scoped type="less">
    @import "css/demo.less";

    :scope {
      display: inline-block;
    }
    button {
      background: @primary;
      color: fadeout(@base, @textfadeout);
      cursor: pointer;
    }
    button when (luma(@primary) < 50%) {
      color: fadeout(@reverse, @textfadeoutreverse);
    }
    button:active {
      background: lighten(@primary,20%);
    }
  </style>
  <script>
    foo () {}
  </script>
</less-import>
```

if I change `type="less"` to `type='less'` everything is fine.
Linux Mint x64 v17.2 + Atom v1.3.2 + language-riot-tag v0.1.1

PS: Maybe an Atom issue? your regexes seem correct.

**Comment by dekimasoon** [comment]
Thank you for reporting the issue!
Hope something wrong in my regexes.
I'll check it tonight or tomorrow. Sorry for your inconvenient.

**Comment by dekimasoon** [comment]
@aMarCruz, I tried to reproduce your issue, but I couldn't.
One possibility I came up with is that the `langulage-less` plugin on your Atom were disabled.
That makes your LESS codes with `type="less"` unhighlighted and codes with `type='less'` highlighted as Pure CSS.
Could you please confirm if your `langulage-less` plugin is enabled?

**Comment by dekimasoon** [comment]
@aMarCruz, I would like to close this issue If it's ok. 
Please let me know if you still have the same problem.

**Comment by aMarCruz** [comment]
@dekimasoon sorry by the delay, yes I have enabled the `language-less` plugin, the issues is still present with Atom 1.5.3 and `languague-riot-tag` 0.2.0 but now with single-quotes :open_mouth:. Using `type="less"` is ok. I will close this issue and tell you if I find more info.
Thanks for your work!
