### ISSUE TITLE
Not recognize heading tag correctly

### ISSUE THREAD

**Issue by leozdgao** [dekimasoon/language-riot-tag#4]
I'm using 0.2.0 and the heading tag is not being recognized correctly.

![image](https://cloud.githubusercontent.com/assets/8381024/13552701/99ea7c90-e3a8-11e5-8a53-99d9d2698d3a.png)

I'm totally new to , but I try to fix it here #3 .

**Comment by dekimasoon** [comment]
Sorry for your inconvinience, and Thanks a lot for your PR :+1: 
Now your PR merged, and I released 0.2.1.

**Comment by leozdgao** [comment]
Glad to help. :smile:
